name       : perl-extutils-installpaths
version    : 0.011
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.011.tar.gz : 7609fa048cdcf1451cad5b1d7d494f30e3d5bad0672d15404f1ea60e1df0067c
license    : Artistic-2.0
component  : programming.perl
summary    : Build.PL install path logic made easy
description: |
    Build.PL install path logic made easy
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
