name       : perl-extutils-installpaths
version    : '0.012'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz : 84735e3037bab1fdffa3c2508567ad412a785c91599db3c12593a50a1dd434ed
license    : Artistic-2.0
component  : programming.perl
summary    : Build.PL install path logic made easy
description: |
    Build.PL install path logic made easy
builddeps :
    - perl-extutils-config
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
